### ISSUE TITLE
When running via HomeAssistant state isn't always correctly reflected

### ISSUE THREAD

**Issue by shortbloke** [Danielhiversen/flux_led#51]
Per issue initially raised against HomeAssistant: https://github.com/home-assistant/home-assistant/issues/11565

Investigation showed that raw data received by flux_led running under HASS was different to flux_led running via the command line and appeared to be sensitive as to how quickly/often it was queried.

A simple test program:
```
import flux_led
from time import sleep
light = flux_led.WifiLedBulb("192.168.200.170")
while True:
    light.update_state(retry=2)
    power_state = light.raw_state[2]
    if power_state == 0x23:
        print("ON")
    elif power_state == 0x24:
        print("OFF")
    sleep(5)
```
Shows that if you change the sleep interval from 5 to 30 seconds, at 5 second pools changes made to the state of the LEDs is captured, at 30 seconds, it can take several minutes before the raw data reflects the current state.

Littering the code with print statements and checking if any errors or timeout in the socket was occurring showed no such evidence. 

I have 4 different device types in use for testing which all exhibit this problem:
 - White UFO (ZJ-WFUF-107F
 - Mini (ZJ-MWIR-RGBW)
 - Sunix White (SU705)
 - Sunix Black (SU794)

**Comment by Danielhiversen** [comment]
Fixed with #52

**Comment by jschmer** [comment]
FYI: I debugged a similar issue just recently. I found out that the connection to my Wifi LED controller is not strictly a logical point-to-point connection. This means that if you have 2 or more clients connected to the same Wifi controller, the clients interfere with each other.

Concrete example: Client X (Magic Home App or flux_led) and Client Y (flux_led) are connected to the same Wifi controller. Client X requests the current status at time _t1_ from the Wifi controller. The Wifi controller responds to both Client X and Client Y with the current status. Client Y never expected a status message without a preceding request, so the data lingers in the receive queue without Client Y noticing. When Client Y requests a status update later at _t2_, it will read the old status data from _t1_ that is still in the receive queue. The same happens with turning the light off or on, the Wifi controller "broadcasts" a response to every connected client.

The workaround is to have only one client connected. A proper solution would be that flux_led reads the full receive buffer and processes all pending messages or it implements an IO loop that always listens for messages.

That's also why reconnecting before querying the state fixes this issue because this will discard the old receive buffer and start from scratch.

**Comment by clydefrog76** [comment]
I am using the home assistant integration and I am seeing this inconsistent behaviour too.
Using the android app, all is well but using the HA integration, the power will switch, once, then never again. If I switch the power on afterwards, the entity in HA will turn on but after 1-2 seconds off again. There is no change in the actual LED strip. Now when I go back to the android app, I need to press the on/off button 4 times, then the LED strip flickers once and now it's syncronized again with the app. Like mentioned above, I think there is an interference between both clients.
